tasks:
  # NOTE: live-reload doesn't work yet
  #       https://github.com/gitpod-io/gitpod/issues/3282
  - init: npm install
    command: |
      export HOST="$(gp url 4200)"

      gp open app/templates/application.hbs
      npm run start -p 4200
      { gp await-port 4200 && sleep 5 && gp preview $HOST & } &> /dev/null
ports:
  - port: 4200
    onOpen: ignore
vscode:
  extensions:
    # Base Glimmer Syntax
    - lifeart.vscode-glimmer-syntax
    # Syntax extensions to other languages
    - chiragpat.vscode-glimmer
    # Language Server for Improved DX in Ember Projects
    - lifeart.vscode-ember-unstable
